---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Présentation du jeu Dilemma"
keywords:    "jeu, écologie, dilemma"
description: "Présentation et téléchargement du jeu dilemma, un jeu de coopétition sur le climat et l'écologie"
source_link: "https://github.com/t413/SinglePaged"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  turquoise: '#0fbfcf'
  grey: '#2D3040'
  yellow: '#F2AE2E'
  orange: '#F29A2E'
  blancasse: '#F2CDAC'
  red: '#D94032'

kramdown:
  auto_ids:  false

